version: 0.0
os: linux

files:
  - source: build/libs/*.jar
    destination: /opt/myapp

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: root
