version: 0.0
os: linux

files:
  - source: build/libs/
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      runas: ec2-user
