version: 0.2

phases:
  pre_build:
    commands:
      - echo "Login to Amazon ECR..."
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 416225317325.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=416225317325.dkr.ecr.ap-southeast-1.amazonaws.com/ai0917-backend-springboot
      - IMAGE_TAG=latest
      - echo "Repository URI = $REPOSITORY_URI"

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building Spring Boot JAR..."
      - chmod +x ./gradlew
      - ./gradlew clean build -x test
      - echo "Building Docker image..."
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker images

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Push completed."
      - printf '[{"name":"ai0917-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json